target-version = "py310"
line-length = 120
exclude = ["runtime/READv2/READ2.py"]

[lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # isort
    "I",
]
